os: linux # Use linux unless specified otherwise.
dist: xenial
sudo: required

language: cpp

matrix:
  include:
    - name: gcc-10
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - CXX_COMPILER=g++-10 CC_COMPILER=gcc-10

    - name: clang-10
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10-multilib # for libstdc++
            - clang-10
      env:
        - CXX_COMPILER=clang++-10 CC_COMPILER=clang-10

install:
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}
  - JOBS=2 # Travis machines have 2 cores.

before_script:
  - rm -rf build
  - mkdir -p build
  - cd build

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug -- -j${JOBS}
  - ctest --output-on-failure -C Debug -j${JOBS}
  - rm -rf ./*

notifications:
  email: false
